/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MindloopRouteImport } from './routes/mindloop'
import { Route as LithosRouteImport } from './routes/lithos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const MindloopRoute = MindloopRouteImport.update({
  id: '/mindloop',
  path: '/mindloop',
  getParentRoute: () => rootRouteImport,
} as any)
const LithosRoute = LithosRouteImport.update({
  id: '/lithos',
  path: '/lithos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lithos': typeof LithosRoute
  '/mindloop': typeof MindloopRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lithos': typeof LithosRoute
  '/mindloop': typeof MindloopRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lithos': typeof LithosRoute
  '/mindloop': typeof MindloopRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lithos' | '/mindloop' | '/api/chat' | '/api/contact'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lithos' | '/mindloop' | '/api/chat' | '/api/contact'
  id: '__root__' | '/' | '/lithos' | '/mindloop' | '/api/chat' | '/api/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LithosRoute: typeof LithosRoute
  MindloopRoute: typeof MindloopRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiContactRoute: typeof ApiContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mindloop': {
      id: '/mindloop'
      path: '/mindloop'
      fullPath: '/mindloop'
      preLoaderRoute: typeof MindloopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lithos': {
      id: '/lithos'
      path: '/lithos'
      fullPath: '/lithos'
      preLoaderRoute: typeof LithosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LithosRoute: LithosRoute,
  MindloopRoute: MindloopRoute,
  ApiChatRoute: ApiChatRoute,
  ApiContactRoute: ApiContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
